# Generated by Django 5.2.8 on 2025-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gamesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Oyun Adı')),
                ('slug', models.SlugField(editable=False, help_text="Oyunun URL'deki adı (örn: dice-wars)", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
            ],
        ),
    ]
