# Generated by Django 5.2.8 on 2025-11-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_minigame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='player2',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='main.minigame'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosted_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='game_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minigame',
            name='max_players',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Max. Oyuncu'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='min_players',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Min. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='board_state',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='minigame',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True),
        ),
    ]
