# Generated by Django 5.2.8 on 2025-11-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_gamesession_player1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='board_size',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Tahta Boyutu (N x N)'),
        ),
    ]
