# Generated by Django 5.2.8 on 2025-11-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gamesession_board_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minigame',
            options={'ordering': ['name'], 'verbose_name': 'Mini Oyun', 'verbose_name_plural': 'Mini Oyunlar'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='per_game_stats',
            field=models.JSONField(default=dict, verbose_name='Oyun Bazlı İstatistikler'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_games',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Oyun'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Kayıp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Toplam Kazanma'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='eliminated_players',
            field=models.JSONField(default=list, verbose_name='Elenmiş Oyuncular'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='invited_players',
            field=models.JSONField(blank=True, default=list, verbose_name='Davetli Oyuncular'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Özel Oda'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='move_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Hamle Sayısı'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='rematch_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_children', to='main.gamesession'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AddField(
            model_name='minigame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
    ]
