# Generated by Django 5.2.8 on 2025-11-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gamesession_board_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='invited_players',
            field=models.JSONField(blank=True, default=list, verbose_name='Davetli Oyuncular'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Özel Oda'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='rematch_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_children', to='main.gamesession'),
        ),
    ]
