# Generated by Django 5.2.8 on 2025-11-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_voicechannel_options_chatmessage_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textchannel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='voicechannel',
            unique_together=set(),
        ),
    ]
