# Generated by Django 5.2.8 on 2025-11-19 21:14

from django.db import migrations, models
import django.db.models.deletion


def delete_orphaned_chatmessages(apps, schema_editor):
    """Delete all ChatMessage records with NULL channel before making field non-nullable"""
    ChatMessage = apps.get_model('main', 'ChatMessage')
    # Delete all messages with NULL channel (orphaned messages)
    ChatMessage.objects.filter(channel__isnull=True).delete()


def reverse_migration(apps, schema_editor):
    """Reverse migration - nothing to do (can't restore deleted messages)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_migrate_chatmessages_to_textchannel'),
    ]

    operations = [
        # First, delete all ChatMessage records with NULL channel
        migrations.RunPython(delete_orphaned_chatmessages, reverse_migration),
        # Then, make the channel field non-nullable
        migrations.AlterField(
            model_name='chatmessage',
            name='channel',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='messages',
                to='main.textchannel'
            ),
        ),
    ]
