# Generated by Django 5.2.8 on 2025-11-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_make_chatmessage_channel_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_settings',
            field=models.JSONField(default=dict, verbose_name='Kullanıcı Ayarları'),
        ),
    ]
