"""
Django settings for python_version project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import json
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Your main project's static folder
]
CSRF_TRUSTED_ORIGINS = [
    'https://rashigo.com',
    # Eğer Nginx'e http ile ulaşıp içeride https'e dönüyorsa, http versiyonunu da ekleyin:
    'http://rashigo.com',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-t+%**n55*%jp9@)kzegmo9f2u$_4gf6hx4e3sbmd1$%hargrfx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "daphne",
    'django.contrib.staticfiles',
    "main",
    "channels",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'main.middleware.OnlineStatusMiddleware',  # Online/offline status tracking
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'python_version.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Language context
                'main.context_processors.online_status',  # Online/offline status
            ],
        },
    },
]

WSGI_APPLICATION = 'python_version.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'nbcsw2_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Custom User Model
AUTH_USER_MODEL = 'main.CustomUser'

LOGIN_REDIRECT_URL = '/'  # Redirect to home after login

# Redirect to user login page after logout (not admin)
LOGOUT_REDIRECT_URL = '/login/'

# URL to redirect to when login is required
LOGIN_URL = '/login/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('tr', 'Türkçe'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Bütün statik dosyaların toplanacağı yer
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

ASGI_APPLICATION = 'python_version.asgi.application' # <-- Proje adınızdaki asgi dosyasını işaret edin
# Örn: Eğer projeniz 'nbsCW2' ise: ASGI_APPLICATION = 'nbsCW2.asgi.application'

# Channel Layer Ayarı (Geliştirme için InMemory)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# COTURN/WebRTC Configuration
# Load ICE servers from JSON file (webrtc_servers.json)
# This file contains all STUN/TURN servers including your personal server and free public servers

WEBRTC_CONFIG_FILE = BASE_DIR / 'webrtc_servers.json'

# Initialize with empty config
COTURN_CONFIG = {
    'ice_servers': []
}

# Load ICE servers from JSON file
try:
    if WEBRTC_CONFIG_FILE.exists():
        with open(WEBRTC_CONFIG_FILE, 'r', encoding='utf-8') as f:
            webrtc_config = json.load(f)
            # Extract ice_servers array (remove 'comment' fields for WebRTC)
            ice_servers = []
            for server in webrtc_config.get('ice_servers', []):
                # Create clean server config (remove comment field)
                clean_server = {}
                if 'urls' in server:
                    clean_server['urls'] = server['urls']
                if 'username' in server:
                    clean_server['username'] = server['username']
                if 'credential' in server:
                    clean_server['credential'] = server['credential']
                if clean_server:  # Only add if not empty
                    ice_servers.append(clean_server)
            
            COTURN_CONFIG['ice_servers'] = ice_servers
            print(f"[WebRTC] Loaded {len(ice_servers)} ICE servers from {WEBRTC_CONFIG_FILE}")
    else:
        print(f"[WebRTC] Warning: {WEBRTC_CONFIG_FILE} not found. Using fallback servers.")
        # Fallback to basic STUN servers if JSON file doesn't exist
        COTURN_CONFIG['ice_servers'] = [
            {'urls': 'stun:stun.l.google.com:19302'},
            {'urls': 'stun:stun1.l.google.com:19302'},
        ]
except Exception as e:
    print(f"[WebRTC] Error loading {WEBRTC_CONFIG_FILE}: {e}")
    # Fallback to basic STUN servers on error
    COTURN_CONFIG['ice_servers'] = [
        {'urls': 'stun:stun.l.google.com:19302'},
        {'urls': 'stun:stun1.l.google.com:19302'},
    ]

# Export as JSON string for frontend (used in views.py)
# This will be serialized and passed to JavaScript via template context
COTURN_CONFIG_JSON = json.dumps(COTURN_CONFIG['ice_servers'])

# ============================================
# EMAIL & TURNSTILE CONFIGURATION
# ============================================
# Load from email_config.json file

EMAIL_CONFIG_FILE = BASE_DIR / 'email_config.json'

# Default values
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'localhost'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
# Load email and turnstile config from JSON file
_email_config = {}
try:
    if EMAIL_CONFIG_FILE.exists():
        with open(EMAIL_CONFIG_FILE, 'r', encoding='utf-8') as f:
            _email_config = json.load(f)
            print(f"[Email] Loaded config from {EMAIL_CONFIG_FILE}")
    else:
        print(f"[Email] Warning: {EMAIL_CONFIG_FILE} not found. Using defaults.")
except Exception as e:
    print(f"[Email] Error loading {EMAIL_CONFIG_FILE}: {e}")

# SMTP settings
_smtp = _email_config.get('smtp', {})
EMAIL_HOST = _smtp.get('host', 'localhost')
EMAIL_PORT = int(_smtp.get('port', 587))
EMAIL_USE_TLS = _smtp.get('use_tls', True)
EMAIL_USE_SSL = _smtp.get('use_ssl', False)
EMAIL_HOST_USER = _smtp.get('username', '')
EMAIL_HOST_PASSWORD = _smtp.get('password', '')

# Email addresses
DEFAULT_FROM_EMAIL = _email_config.get('from_email', 'noreply@rashigo.com')
SERVER_EMAIL = _email_config.get('server_email', 'admin@rashigo.com')

# Cloudflare Turnstile
_turnstile = _email_config.get('cloudflare_turnstile', {})
TURNSTILE_SITE_KEY = _turnstile.get('site_key', '')
TURNSTILE_SECRET_KEY = _turnstile.get('secret_key', '')

print(f"[Email] SMTP Host: {EMAIL_HOST}:{EMAIL_PORT}")

# For testing, use Cloudflare's test keys if none configured
if DEBUG and not TURNSTILE_SITE_KEY:
    TURNSTILE_SITE_KEY = '1x00000000000000000000AA'
    TURNSTILE_SECRET_KEY = '1x0000000000000000000000000000000AA'
    print("[Turnstile] Using Cloudflare test keys (DEBUG mode)")

# Email verification expiry (in seconds)
EMAIL_VERIFICATION_EXPIRY = 600  # 10 minutes
