"""
Django settings for python_version project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Your main project's static folder
]
CSRF_TRUSTED_ORIGINS = [
    'https://rashigo.com',
    # Eğer Nginx'e http ile ulaşıp içeride https'e dönüyorsa, http versiyonunu da ekleyin:
    'http://rashigo.com',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-t+%**n55*%jp9@)kzegmo9f2u$_4gf6hx4e3sbmd1$%hargrfx')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "daphne",
    'django.contrib.staticfiles',
    "main",
    "channels",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'python_version.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # Language context
            ],
        },
    },
]

WSGI_APPLICATION = 'python_version.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'nbcsw2_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Custom User Model
AUTH_USER_MODEL = 'main.CustomUser'

LOGIN_REDIRECT_URL = '/' # Kök dizine (anasayfaya) yönlendir

# Kullanıcının giriş yapması gerektiğinde yönlendirileceği URL'in adı
LOGIN_URL = '/login/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('tr', 'Türkçe'),
    ('es', 'Español'),
    ('fr', 'Français'),
    ('de', 'Deutsch'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Bütün statik dosyaların toplanacağı yer
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

ASGI_APPLICATION = 'python_version.asgi.application' # <-- Proje adınızdaki asgi dosyasını işaret edin
# Örn: Eğer projeniz 'nbsCW2' ise: ASGI_APPLICATION = 'nbsCW2.asgi.application'

# Channel Layer Ayarı (Geliştirme için InMemory)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# COTURN/WebRTC Configuration (Backend settings - one server handles all voice channels)
# SECURITY: Load credentials from environment variables
COTURN_HOST = os.getenv('COTURN_HOST', 'localhost')
COTURN_PORT = os.getenv('COTURN_PORT', '3478')
COTURN_USERNAME = os.getenv('COTURN_USERNAME', '')
COTURN_PASSWORD = os.getenv('COTURN_PASSWORD', '')

COTURN_CONFIG = {
    'ice_servers': []
}

# Add COTURN server if credentials are provided
if COTURN_HOST and COTURN_USERNAME and COTURN_PASSWORD:
    COTURN_CONFIG['ice_servers'].append({
        'urls': [
            f'stun:{COTURN_HOST}:{COTURN_PORT}',
            f'turn:{COTURN_HOST}:{COTURN_PORT}'
        ],
        'username': COTURN_USERNAME,
        'credential': COTURN_PASSWORD,
    })

# Add public STUN servers (always available)
COTURN_CONFIG['ice_servers'].extend([
    {'urls': ['stun:stun.l.google.com:19302']},
    {'urls': ['stun:stun1.l.google.com:19302']},
    {'urls': ['stun:stun2.l.google.com:19302']},
    {'urls': ['stun:stun3.l.google.com:19302']},
    {'urls': ['stun:stun.stunprotocol.org:3478']},
    {'urls': ['stun:stun.ekiga.net:3478']},
])
